# Copernicus Global Land Service: Land Cover 100m: version 3.0.1
# https://land.copernicus.eu/global/products/lc

# path can be:
#  - absolute path (e.g. C:\Users\maffelu.ISIS\Downloads\PROBAV_LC100_global_v3.0.1_2019-nrt_Discrete-Classification-map_EPSG-4326.tif)
#  - relative path to the YAML file location (e.g.  ./data/training/PROBAV_LC100_global_v3.0.1_2019-nrt_Discrete-Classification-map_EPSG-4326.tif)
# by default it is stored in  the github local repository at ./ghslc/test/data/training
filename: ./test/data/training/PROBAV_LC100_global_v3.0.1_2019-nrt_Discrete-Classification-map_EPSG-4326.tif

url: https://zenodo.org/record/3939050/files/PROBAV_LC100_global_v3.0.1_2019-nrt_Discrete-Classification-map_EPSG-4326.tif?download=1
classes:
    0: "No input data available"
    111: "Closed forest, evergreen needle leaf"
    113: "Closed forest, deciduous needle leaf"
    112: "Closed forest, evergreen, broad leaf"
    114: "Closed forest, deciduous broad leaf"
    115: "Closed forest, mixed"
    116: "Closed forest, unknown"
    121: "Open forest, evergreen needle leaf"
    123: "Open forest, deciduous needle leaf"
    122: "Open forest, evergreen broad leaf"
    124: "Open forest, deciduous broad leaf"
    125: "Open forest, mixed"
    126: "Open forest, unknown"
    20: "Shrubs"
    30: "Herbaceous vegetation"
    90: "Herbaceous wetland"
    100: "Moss and lichen"
    60: "Bare / sparse vegetation"
    40: "Cultivated and managed vegetation/agriculture (cropland)"
    50: "Urban / built up"
    70: "Snow and Ice"
    80: "Permanent water bodies"
    200: "Open sea"
